# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Global values
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

default_platform(:ios)

platform :ios do
  
  private_lane :prepare_app_store_connect_api_key do
  app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY_CONTENT_BASE64"],
        is_key_content_base64: true
        )
  end

  desc "import certificate and provisioning profile" 
  private_lane :import_certificate_and_provisioning_profile do
    prepare_app_store_connect_api_key
    
    create_keychain(
        name: "mykeychain",
        password: ENV["KEYCHAIN_PASSWORD"]
        )
    import_certificate(
        certificate_path: "ios_distribution.p12",
        certificate_password: ENV["P12_PASSWORD"],
        keychain_name: "mykeychain",
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
        )
    install_provisioning_profile(path: "odai_app_store.mobileprovision")
  end
  
  lane :build_ipa do
  # add actions here: https://docs.fastlane.tools/actions
    import_certificate_and_provisioning_profile
    build_app(
      project: "odai.xcodeproj",
      clean: true,
      configuration: "Release",
      silent: true,
      skip_package_ipa: true,
      include_bitcode: false,
      skip_archive: true,
      skip_codesigning: true,
      xcargs: "-allowProvisioningUpdates",
      cloned_source_packages_path: "SourcePackages"
    )
  end
  
  desc "Description of what the lane does"
  lane :upload_testflight do
    build_ipa
    upload_to_testflight(
        username: ENV["USERNAME"]
        )
  end
  
  
end
