name: build-ios-app

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macOS-12
            
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Prepare keychain.p12
      run: |
        echo "${{ secrets.BUILD_CERTIFICATE_BASE64 }}" > ios_distribution.p12.txt
        base64 --decode ios_distribution.p12.txt > ios_distribution.p12
      
    - name: Update bundler
      run: gem update bundler && bundle -v && which bundle
      
    - name: Install bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      
    - name: Cache SPM
      uses: actions/cache@v3
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Fastlane
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_CONTENT_BASE64: ${{ secrets.ASC_KEY_CONTENT_BASE64 }}
        USERNAME: ${{ secrets.USERNAME }}
      run: bundle exec fastlane ios build_ipa
