name: build-ios-app

on: 
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-12
            
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Decode keychain.p12
      run: |
        echo "${{ secrets.BUILD_CERTIFICATE_BASE64 }}" > ios_distribution.p12.txt
        base64 --decode ios_distribution.p12.txt > ios_distribution.p12
    
    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.APP_STORE_PROVISIONING_PROFILE }}" > odai_app_store.mobileprovision.txt
        base64 --decode odai_app_store.mobileprovision.txt > odai_app_store.mobileprovision
        
    - name: Decode App Store Connect API Key
      run: |
        echo "${{ secrets.ASC_KEY_CONTENT_BASE64 }}" > AuthKey_${{ secrets.ASC_KEY_ID }}.p8.txt
        base64 --decode AuthKey_${{ secrets.ASC_KEY_ID }}.p8.txt > AuthKey_${{ secrets.ASC_KEY_ID }}.p8
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true
        
    - name: Update bundler
      run: gem update bundler && bundle -v && which bundle
      
    - name: Install bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      
    - name: Cache SPM
      uses: actions/cache@v3
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Setup SSH Keys and known_hosts for fastlane match
      # Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
      run: |
        SSH_PATH="$HOME/.ssh"

        mkdir -p "$SSH_PATH"
        touch "$SSH_PATH/known_hosts"

        echo "$PRIVATE_KEY" > "$SSH_PATH/id_ecdsa"

        chmod 700 "$SSH_PATH"
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 600 "$SSH_PATH/known_hosts"
        chmod 600 "$SSH_PATH/id_ecdsa"

        eval $(ssh-agent)
        ssh-add "$SSH_PATH/id_ecdsa"
      env:
        PRIVATE_KEY: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
    
    - name: Fastlane
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_CONTENT_BASE64: ${{ secrets.ASC_KEY_CONTENT_BASE64 }},
        USERNAME: ${{ secrets.USERNAME }},
        TEAM_ID: ${{ secrets.TEAM_ID }},
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: bundle exec fastlane ios build_ipa
      timeout-minutes: 40

#     - name: Archive
#       run: |        
#         xcodebuild \
#           archive \
#           CODE_SIGNING_REQUIRED=NO \
#           CODE_SIGNING_ALLOWED=NO \
#           -project odai.xcodeproj \
#           -scheme "odai" \
#           -configuration Release \
#           -quiet \
#           -clonedSourcePackagesDirPath SourcePackages
          
#     - name: Export ipa
#       run: |
#         xcodebuild \
#           -exportArchive \
#           -archivePath "${{ github.workspace }}" \
#           -authenticationKeyPath "${{ github.workspace }}/AuthKey_${{ secrets.ASC_KEY_ID }}.p8" \
#           -authenticationKeyID "${{ secrets.ASC_KEY_ID }}" \
#           -authenticationKeyIssuerID "${{ secrets.ASC_ISSUER_ID }}" \
#           -allowProvisioningUpdates
