name: Create a Release Pull Request

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby#caching-dependencies
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Bump minor version then create a release branch and tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          bundle exec fastlane bump_minor

      - name: Create a pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(agvtool what-marketing-version -terse1)
          BODY=$(gh api --method POST -H "Accept: application/vnd.github+json" /repos/{owner}/{repo}/releases/generate-notes -f tag_name="v$VERSION" -f target_commitish='main' | jq --raw-output .body)
          gh pr create --base main --head "release/v$VERSION" --title "release v$VERSION" --body "$BODY"
