# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
      
name: Swift

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild
            -scheme Swift-github-actions
            -sdk iphonesimulator
            -configuration Debug
            build
    - name: Run tests
      run: xcodebuild
            -scheme Swift-github-actions
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max'
            clean test
